<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33810" started-at="2021-12-22T06:36:04Z" finished-at="2021-12-22T06:36:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33810" started-at="2021-12-22T06:36:04Z" finished-at="2021-12-22T06:36:38Z">
      <class name="DataDriven.ReadExcel">
        <test-method status="PASS" signature="setbrowser()[pri:0, instance:DataDriven.ReadExcel@10bdf5e5]" name="setbrowser" is-config="true" duration-ms="8710" started-at="2021-12-22T12:06:04Z" finished-at="2021-12-22T12:06:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setbrowser -->
        <test-method status="PASS" signature="demoClass(java.lang.String, java.lang.String)[pri:0, instance:DataDriven.ReadExcel@10bdf5e5]" name="demoClass" duration-ms="9413" started-at="2021-12-22T12:06:14Z" data-provider="testdata" finished-at="2021-12-22T12:06:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16opencart@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mini]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoClass -->
        <test-method status="FAIL" signature="demoClass(java.lang.String, java.lang.String)[pri:0, instance:DataDriven.ReadExcel@10bdf5e5]" name="demoClass" duration-ms="7295" started-at="2021-12-22T12:06:24Z" data-provider="testdata" finished-at="2021-12-22T12:06:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[miniproject2511@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mini]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at DataDriven.ReadExcel.demoClass(ReadExcel.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoClass -->
        <test-method status="FAIL" signature="demoClass(java.lang.String, java.lang.String)[pri:0, instance:DataDriven.ReadExcel@10bdf5e5]" name="demoClass" duration-ms="7014" started-at="2021-12-22T12:06:31Z" data-provider="testdata" finished-at="2021-12-22T12:06:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[miniproject]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mini]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at DataDriven.ReadExcel.demoClass(ReadExcel.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoClass -->
        <test-method status="PASS" signature="down()[pri:0, instance:DataDriven.ReadExcel@10bdf5e5]" name="down" is-config="true" duration-ms="111" started-at="2021-12-22T12:06:38Z" finished-at="2021-12-22T12:06:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- DataDriven.ReadExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
